### ISSUE TITLE
Social Media links to be open in a new tab

### ISSUE THREAD

**Issue by hardiksharma02** [TEDxJUET/TedxJUET#7]
the media links in the footer must open in a new tab .

**Comment by Arkhein6** [comment]
I would like to work on this?

**Comment by Abishkardhenga** [comment]
heyy  @hardiksharma02  I am interested in this topic. Can You assign it to me .?

**Comment by Prthmsh7** [comment]
> the media links in the footer must open in a new tab .

assign this issue to me. I can fix this.
